version: '3.8'
services:
    api-service:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
        networks:
          - api-network

networks:
  api-network:
    external: false