version: '3.8'
services:
    api-service:
        build: .
        volumes:
            - ./api/:/usr/src/api
        ports:
            - 6000:6000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
        networks:
          - api-network

networks:
  api-network:
    external: false